using AutoMapper;
using Application.DTOs.Employee;
using Application.Employees.DTOs;
using Domain;
using Application.Employees.DTOs.Personal;
using Application.Employees.DTOs.Services;
using Application.Employees.DTOs.Experience;
using Application.Employees.DTOs.Employee;

namespace Application.Core;

public class MappingProfiles : Profile
{
    public MappingProfiles()
    {
        CreateMap<Employee, EmployeeListDto>()
            .ForMember(dest => dest.AM, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.FirstName + " " + src.LastName))
            .ForMember(dest => dest.Afm, opt => opt.MapFrom(src => src.Afm))
            .ForMember(dest => dest.Address, opt => opt.MapFrom(src => src.Directorate))
            .ForMember(dest => dest.Sector, opt => opt.MapFrom(src => src.Sector))
            .ForMember(dest => dest.Department, opt => opt.MapFrom(src => src.Department))
            .ForMember(dest => dest.Office, opt => opt.MapFrom(src => src.Office))
            .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
            .ForMember(dest => dest.Mk, opt => opt.MapFrom(src => src.MK))
            .ForMember(dest => dest.MkDate, opt => opt.MapFrom(src => src.MKDate))
            .ForMember(dest => dest.MkNextDate, opt => opt.MapFrom(src => src.MKNextDate))
            .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category));

        CreateMap<Employee, EmployeeCard>()
            .ForMember(dest => dest.PostCode, opt => opt.MapFrom(src => src.PostCode))
            .ForMember(dest => dest.Iban1, opt => opt.MapFrom(src => src.Iban1))
            .ForMember(dest => dest.Iban2, opt => opt.MapFrom(src => src.Iban2))
            .ForMember(dest => dest.BirthDate, opt => opt.MapFrom(src => src.BirthDate.HasValue ? src.BirthDate.Value.ToString("yyyy-MM-dd") : ""))
            .ForMember(dest => dest.IdentityCardIssueDate, opt => opt.MapFrom(src => src.IdentityCardIssueDate.HasValue ? src.IdentityCardIssueDate.Value.ToString("yyyy-MM-dd") : ""))
            .ForMember(dest => dest.Sex, opt => opt.MapFrom(src => src.Sex.ToString()))
            .ForMember(dest => dest.FamilyStatus, opt => opt.MapFrom(src => src.FamilyStatus.ToString()))
            .ForMember(dest => dest.Ama, opt => opt.MapFrom(src => src.Ama))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.PersonalNumber, opt => opt.MapFrom(src => src.PersonalNumber))
            .ForMember(dest => dest.Specialty, opt => opt.MapFrom(src => src.Specialty))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.FirstName + " " + src.LastName))
            .ForMember(dest => dest.Department, opt => opt.MapFrom(src => ""))
            .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
            .ForMember(dest => dest.EmploymentState, opt => opt.MapFrom(src => src.IsActive.ToString()))
            .ForMember(dest => dest.TerminationDate, opt => opt.MapFrom(src => src.TerminationDate));

        CreateMap<EmployeeCard, Employee>()
            .ForMember(dest => dest.PostCode, opt => opt.MapFrom(src => src.PostCode))
            .ForMember(dest => dest.BirthDate, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.BirthDate) ? (DateOnly?)null : DateOnly.Parse(src.BirthDate)))
            .ForMember(dest => dest.IdentityCardIssueDate, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.IdentityCardIssueDate) ? (DateOnly?)null : DateOnly.Parse(src.IdentityCardIssueDate)))
            .ForMember(dest => dest.Sex, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.Sex) ? 0 : int.Parse(src.Sex)))
            .ForMember(dest => dest.FamilyStatus, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.FamilyStatus) ? 0 : int.Parse(src.FamilyStatus)))
            .ForMember(dest => dest.Ama, opt => opt.MapFrom(src => src.Ama))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Iban1, opt => opt.MapFrom(src => src.Iban1))
            .ForMember(dest => dest.Iban2, opt => opt.MapFrom(src => src.Iban2))
            .ForMember(dest => dest.FatherName, opt => opt.MapFrom(src => src.FatherName))
            .ForMember(dest => dest.MotherName, opt => opt.MapFrom(src => src.MotherName))
            .ForMember(dest => dest.Doy, opt => opt.MapFrom(src => src.Doy))
            .ForMember(dest => dest.PersonalNumber, opt => opt.MapFrom(src => src.PersonalNumber))
            .ForMember(dest => dest.Specialty, opt => opt.MapFrom(src => src.Specialty))
            .ForMember(dest => dest.MK, opt => opt.MapFrom(src => src.Mk))
            .ForMember(dest => dest.MKDate, opt => opt.MapFrom(src => src.MkDate))
            .ForMember(dest => dest.MKNextDate, opt => opt.MapFrom(src => src.MkNextDate))
            .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.EmploymentState) ? 0 : int.Parse(src.EmploymentState)));

        CreateMap<EmployeePersonal, Employee>()
            .ForMember(dest => dest.BirthDate, opt => opt.MapFrom(src => src.BirthDate))
            .ForMember(dest => dest.FamilyStatus, opt => opt.MapFrom(src => src.FamilyStatus))
            .ForMember(dest => dest.FatherName, opt => opt.MapFrom(src => src.FatherName))
            .ForMember(dest => dest.MotherName, opt => opt.MapFrom(src => src.MotherName));

        CreateMap<EmployeeInfo, Employee>()
            .ForMember(dest => dest.Address, opt => opt.MapFrom(src => src.Address))
            .ForMember(dest => dest.City, opt => opt.MapFrom(src => src.City))
            .ForMember(dest => dest.PostCode, opt => opt.MapFrom(src => src.PostCode))
            .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
            .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email));

        CreateMap<EmployeeIdentity, Employee>()
            .ForMember(dest => dest.Citizenship, opt => opt.MapFrom(src => src.Citizenship))
            .ForMember(dest => dest.Nationality, opt => opt.MapFrom(src => src.Nationality))
            .ForMember(dest => dest.IdentityCardNumber, opt => opt.MapFrom(src => src.IdentityCardNumber))
            .ForMember(dest => dest.IdentityCardIssueDate, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.IdentityCardIssueDate) ? (DateOnly?)null : DateOnly.Parse(src.IdentityCardIssueDate)));

        CreateMap<EmployeeNumber, Employee>()
            .ForMember(dest => dest.Afm, opt => opt.MapFrom(src => src.Afm))
            .ForMember(dest => dest.Ama, opt => opt.MapFrom(src => src.Ama))
            .ForMember(dest => dest.Amka, opt => opt.MapFrom(src => src.Amka))
            .ForMember(dest => dest.PersonalNumber, opt => opt.MapFrom(src => src.PersonalNumber))
            .ForMember(dest => dest.Doy, opt => opt.MapFrom(src => src.Doy));

        CreateMap<EmployeeBank, Employee>()
            .ForMember(dest => dest.Iban1, opt => opt.MapFrom(src => src.Iban1))
            .ForMember(dest => dest.Iban2, opt => opt.MapFrom(src => src.Iban2));

        CreateMap<EmployeeBelongs, Employee>()
            .ForMember(dest => dest.Directorate, opt => opt.MapFrom(src => src.Directorate))
            .ForMember(dest => dest.Sector, opt => opt.MapFrom(src => src.Sector))
            .ForMember(dest => dest.Department, opt => opt.MapFrom(src => src.Department))
            .ForMember(dest => dest.Office, opt => opt.MapFrom(src => src.Office));

        CreateMap<EmployeeWorks, Employee>()
            .ForMember(dest => dest.WorkDirectorate, opt => opt.MapFrom(src => src.WorkDirectorate))
            .ForMember(dest => dest.WorkSector, opt => opt.MapFrom(src => src.WorkSector))
            .ForMember(dest => dest.WorkDepartment, opt => opt.MapFrom(src => src.WorkDepartment))
            .ForMember(dest => dest.WorkOffice, opt => opt.MapFrom(src => src.WorkOffice));

        CreateMap<Employee, EmployeeService>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.HireDate, opt => opt.MapFrom(src => src.HireDate))
            .ForMember(dest => dest.PublicationDate, opt => opt.MapFrom(src => src.PublicationDate))
            .ForMember(dest => dest.AppointmentDate, opt => opt.MapFrom(src => src.AppointmentDate))
            .ForMember(dest => dest.TerminationDate, opt => opt.MapFrom(src => src.TerminationDate))
            .ForMember(dest => dest.MKDate, opt => opt.MapFrom(src => src.MKDate))
            .ForMember(dest => dest.MKNextDate, opt => opt.MapFrom(src => src.MKNextDate))
            .ForMember(dest => dest.RankDate, opt => opt.MapFrom(src => src.RankDate))
            //.ForMember(dest => dest.RankNextDate, opt => opt.MapFrom(src => src.RankNextDate))
            .ForMember(dest => dest.WorkRelation, opt => opt.MapFrom(src => src.WorkRelation))
            .ForMember(dest => dest.Position, opt => opt.MapFrom(src => src.Position))
            .ForMember(dest => dest.EmploymentType, opt => opt.MapFrom(src => src.EmploymentType))
            .ForMember(dest => dest.MK, opt => opt.MapFrom(src => src.MK))
            .ForMember(dest => dest.SalaryGrade, opt => opt.MapFrom(src => src.SalaryGrade))
            .ForMember(dest => dest.SalaryCode, opt => opt.MapFrom(src => src.SalaryCode))
            .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category))
            .ForMember(dest => dest.Branch, opt => opt.MapFrom(src => src.Branch))
            .ForMember(dest => dest.Specialty, opt => opt.MapFrom(src => src.Specialty))
            .ForMember(dest => dest.Rank, opt => opt.MapFrom(src => src.Rank))
            .ForMember(dest => dest.Fek, opt => opt.MapFrom(src => src.Fek))
            .ForMember(dest => dest.GradeFek, opt => opt.MapFrom(src => src.GradeFek))
            .ForMember(dest => dest.Directorate, opt => opt.MapFrom(src => src.Directorate))
            .ForMember(dest => dest.Sector, opt => opt.MapFrom(src => src.Sector))
            .ForMember(dest => dest.Department, opt => opt.MapFrom(src => src.Department))
            .ForMember(dest => dest.Office, opt => opt.MapFrom(src => src.Office))
            .ForMember(dest => dest.WorkDirectorate, opt => opt.MapFrom(src => src.WorkDirectorate))
            .ForMember(dest => dest.WorkSector, opt => opt.MapFrom(src => src.WorkSector))
            .ForMember(dest => dest.WorkDepartment, opt => opt.MapFrom(src => src.WorkDepartment))
            .ForMember(dest => dest.WorkOffice, opt => opt.MapFrom(src => src.WorkOffice))
            .ForMember(dest => dest.Flag, opt => opt.MapFrom(src => src.Flag));

        // Experience mappings
        CreateMap<Experience, EmployeeExperience>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.DateFrom, opt => opt.MapFrom(src => src.DateFrom))
            .ForMember(dest => dest.DateTo, opt => opt.MapFrom(src => src.DateTo))
            .ForMember(dest => dest.Years, opt => opt.MapFrom(src => src.Years))
            .ForMember(dest => dest.Months, opt => opt.MapFrom(src => src.Months))
            .ForMember(dest => dest.Days, opt => opt.MapFrom(src => src.Days))
            .ForMember(dest => dest.Carrier, opt => opt.MapFrom(src => src.Carrier))
            .ForMember(dest => dest.DecisionId, opt => opt.MapFrom(src => src.DecisionId))
            .ForMember(dest => dest.Comments, opt => opt.MapFrom(src => src.Comments))
            .ForMember(dest => dest.Agonis, opt => opt.MapFrom(src => src.Agonis))
            .ForMember(dest => dest.Mk, opt => opt.MapFrom(src => src.Mk))
            .ForMember(dest => dest.Grade, opt => opt.MapFrom(src => src.Grade))
            .ForMember(dest => dest.Sunt, opt => opt.MapFrom(src => src.Sunt))
            .ForMember(dest => dest.DateCouncil, opt => opt.MapFrom(src => src.DateCouncil))
            .ForMember(dest => dest.Auto, opt => opt.MapFrom(src => src.Auto));

        CreateMap<EmployeeExperience, Experience>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.DateFrom, opt => opt.MapFrom(src => src.DateFrom))
            .ForMember(dest => dest.DateTo, opt => opt.MapFrom(src => src.DateTo))
            .ForMember(dest => dest.Years, opt => opt.MapFrom(src => src.Years))
            .ForMember(dest => dest.Months, opt => opt.MapFrom(src => src.Months))
            .ForMember(dest => dest.Days, opt => opt.MapFrom(src => src.Days))
            .ForMember(dest => dest.Carrier, opt => opt.MapFrom(src => src.Carrier))
            .ForMember(dest => dest.DecisionId, opt => opt.MapFrom(src => src.DecisionId))
            .ForMember(dest => dest.Comments, opt => opt.MapFrom(src => src.Comments))
            .ForMember(dest => dest.Agonis, opt => opt.MapFrom(src => src.Agonis))
            .ForMember(dest => dest.Mk, opt => opt.MapFrom(src => src.Mk))
            .ForMember(dest => dest.Grade, opt => opt.MapFrom(src => src.Grade))
            .ForMember(dest => dest.Sunt, opt => opt.MapFrom(src => src.Sunt))
            .ForMember(dest => dest.DateCouncil, opt => opt.MapFrom(src => src.DateCouncil))
            .ForMember(dest => dest.Auto, opt => opt.MapFrom(src => src.Auto));

        // Leave mappings
        CreateMap<Leave, Leave>()
            .ForMember(dest => dest.Id, opt => opt.Ignore());

        // Penalty mappings
        CreateMap<Penalty, Penalty>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.Lexical, opt => opt.MapFrom(src => src.Lexical))
            .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
            .ForMember(dest => dest.Decision, opt => opt.MapFrom(src => src.Decision))
            .ForMember(dest => dest.DateFrom, opt => opt.MapFrom(src => src.DateFrom))
            .ForMember(dest => dest.DateTo, opt => opt.MapFrom(src => src.DateTo))
            .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Amount))
            .ForMember(dest => dest.Flag, opt => opt.MapFrom(src => src.Flag));

        // Move mappings
        CreateMap<Move, Move>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.Destination, opt => opt.MapFrom(src => src.Destination))
            .ForMember(dest => dest.Foreas, opt => opt.MapFrom(src => src.Foreas))
            .ForMember(dest => dest.DateFrom, opt => opt.MapFrom(src => src.DateFrom))
            .ForMember(dest => dest.DateTo, opt => opt.MapFrom(src => src.DateTo))
            .ForMember(dest => dest.Decision, opt => opt.MapFrom(src => src.Decision))
            .ForMember(dest => dest.DateDecision, opt => opt.MapFrom(src => src.DateDecision))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment));

        CreateMap<Children, Children>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.EmployeeId, opt => opt.MapFrom(src => src.EmployeeId))
            .ForMember(dest => dest.ChildSurname, opt => opt.MapFrom(src => src.ChildSurname))
            .ForMember(dest => dest.ChildName, opt => opt.MapFrom(src => src.ChildName))
            .ForMember(dest => dest.ChildFather, opt => opt.MapFrom(src => src.ChildFather))
            .ForMember(dest => dest.ChildSex, opt => opt.MapFrom(src => src.ChildSex))
            .ForMember(dest => dest.ChildBirth, opt => opt.MapFrom(src => src.ChildBirth))
            .ForMember(dest => dest.ChildDateFrom, opt => opt.MapFrom(src => src.ChildDateFrom))
            .ForMember(dest => dest.ChildDateTo, opt => opt.MapFrom(src => src.ChildDateTo))
            .ForMember(dest => dest.ChildDisability, opt => opt.MapFrom(src => src.ChildDisability))
            .ForMember(dest => dest.ChildLevel, opt => opt.MapFrom(src => src.ChildLevel))
            .ForMember(dest => dest.ChildSchool, opt => opt.MapFrom(src => src.ChildSchool))
            .ForMember(dest => dest.ChildYears, opt => opt.MapFrom(src => src.ChildYears))
            .ForMember(dest => dest.ChildMonths, opt => opt.MapFrom(src => src.ChildMonths))
            .ForMember(dest => dest.ChildFlag, opt => opt.MapFrom(src => src.ChildFlag))
            .ForMember(dest => dest.Child18, opt => opt.MapFrom(src => src.Child18))
            .ForMember(d => d.ChildSchoolDesc, o => o.MapFrom(s => s.ChildSchoolDesc));

        CreateMap<Studies, Studies>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
            .ForMember(dest => dest.Education, opt => opt.MapFrom(src => src.Education))
            .ForMember(dest => dest.Local, opt => opt.MapFrom(src => src.Local))
            .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category))
            .ForMember(dest => dest.Years, opt => opt.MapFrom(src => src.Years))
            .ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date))
            .ForMember(dest => dest.Degree, opt => opt.MapFrom(src => src.Degree))
            .ForMember(dest => dest.Employee, opt => opt.MapFrom(src => src.Employee))
            .ForMember(dest => dest.Relevance, opt => opt.MapFrom(src => src.Relevance))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
            .ForMember(dest => dest.DateRequired, opt => opt.MapFrom(src => src.DateRequired))
            .ForMember(dest => dest.Location, opt => opt.MapFrom(src => src.Location));
            
        CreateMap<Domain.Changes, Domain.Changes>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.AM, opt => opt.MapFrom(src => src.AM))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.PreviousState, opt => opt.MapFrom(src => src.PreviousState))
            .ForMember(dest => dest.NextState, opt => opt.MapFrom(src => src.NextState  ))
            .ForMember(dest => dest.NextDate, opt => opt.MapFrom(src => src.NextDate))
            .ForMember(dest => dest.User, opt => opt.MapFrom(src => src.User))
            .ForMember(dest => dest.Notes, opt => opt.MapFrom(src => src.Notes))
            .ForMember(dest => dest.AnadromikaApo, opt => opt.MapFrom(src => src.AnadromikaApo))
            .ForMember(dest => dest.AnadromikaEws, opt => opt.MapFrom(src => src.AnadromikaEws))
            .ForMember(dest => dest.Days, opt => opt.MapFrom(src => src.Days))
            .ForMember(dest => dest.Flag, opt => opt.MapFrom(src => src.Flag))
            .ForMember(dest => dest.FlagHRM, opt => opt.MapFrom(src => src.FlagHRM))
            .ForMember(dest => dest.Protocol, opt => opt.MapFrom(src => src.Protocol));

        CreateMap<Placement, Placement>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Am, opt => opt.MapFrom(src => src.Am))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Type))
            .ForMember(dest => dest.OldAddress, opt => opt.MapFrom(src => src.OldAddress))
            .ForMember(dest => dest.OldDepartment, opt => opt.MapFrom(src => src.OldDepartment))
            .ForMember(dest => dest.OldSector, opt => opt.MapFrom(src => src.OldSector))
            .ForMember(dest => dest.OldTeam, opt => opt.MapFrom(src => src.OldTeam))
            .ForMember(dest => dest.NewAddress, opt => opt.MapFrom(src => src.NewAddress))
            .ForMember(dest => dest.NewDepartment, opt => opt.MapFrom(src => src.NewDepartment))
            .ForMember(dest => dest.NewSector, opt => opt.MapFrom(src => src.NewSector))
            .ForMember(dest => dest.NewTeam, opt => opt.MapFrom(src => src.NewTeam))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
            .ForMember(dest => dest.User, opt => opt.MapFrom(src => src.User))
            .ForMember(dest => dest.Duration, opt => opt.MapFrom(src => src.Duration))
            .ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Date));

        CreateMap<AddEmployeeDto, Employee>()
            .ForMember(d => d.FirstName, o => o.MapFrom(s => s.Personal.FirstName))
            .ForMember(d => d.LastName, o => o.MapFrom(s => s.Personal.LastName))
            .ForMember(d => d.BirthDate, o => o.MapFrom(s => s.Personal.BirthDate))
            .ForMember(d => d.FatherName, o => o.MapFrom(s => s.Personal.FatherName))
            .ForMember(d => d.MotherName, o => o.MapFrom(s => s.Personal.MotherName))
            .ForMember(d => d.FamilyStatus, o => o.MapFrom(s => s.Personal.FamilyStatus))
            .ForMember(d => d.Address, o => o.MapFrom(s => s.Personal.Address))
            .ForMember(d => d.City, o => o.MapFrom(s => s.Personal.City))
            .ForMember(d => d.PostCode, o => o.MapFrom(s => s.Personal.PostCode))
            .ForMember(d => d.Phone, o => o.MapFrom(s => s.Personal.Phone))
            .ForMember(d => d.Email, o => o.MapFrom(s => s.Personal.Email))
            .ForMember(d => d.IdentityCardNumber, o => o.MapFrom(s => s.Personal.IdentityCardNumber))
            .ForMember(d => d.IdentityCardIssueDate, o => o.MapFrom(s => s.Personal.IdentityCardIssueDate))
            .ForMember(d => d.Citizenship, o => o.MapFrom(s => s.Personal.Citizenship))
            .ForMember(d => d.Nationality, o => o.MapFrom(s => s.Personal.Nationality))
            .ForMember(d => d.Afm, o => o.MapFrom(s => s.Personal.Afm))
            .ForMember(d => d.Amka, o => o.MapFrom(s => s.Personal.Amka))
            .ForMember(d => d.Ama, o => o.MapFrom(s => s.Personal.Ama))
            .ForMember(d => d.PersonalNumber, o => o.MapFrom(s => s.Personal.PersonalNumber))
            .ForMember(d => d.Doy, o => o.MapFrom(s => s.Personal.Doy))
            .ForMember(d => d.Iban1, o => o.MapFrom(s => s.Personal.Iban1))
            .ForMember(d => d.Iban2, o => o.MapFrom(s => s.Personal.Iban2))
            .ForMember(d => d.WorkRelation, o => o.MapFrom(s => s.Service.WorkRelation))
            .ForMember(d => d.Category, o => o.MapFrom(s => s.Service.Category))
            .ForMember(d => d.Specialty, o => o.MapFrom(s => s.Service.Specialty))
            .ForMember(d => d.Branch, o => o.MapFrom(s => s.Service.Branch))
            .ForMember(d => d.Position, o => o.MapFrom(s => s.Service.Position))
            .ForMember(d => d.EmploymentType, o => o.MapFrom(s => s.Service.EmploymentType))
            .ForMember(d => d.HireDate, o => o.MapFrom(s => s.Service.HireDate))
            .ForMember(d => d.Fek, o => o.MapFrom(s => s.Service.Fek))
            .ForMember(d => d.SalaryCode, o => o.MapFrom(s => s.Service.SalaryCode))
            .ForMember(d => d.MK, o => o.MapFrom(s => s.Service.MK))
            .ForMember(d => d.MKDate, o => o.MapFrom(s => s.Service.MKDate))
            .ForMember(d => d.MKNextDate, o => o.MapFrom(s => s.Service.MKNextDate))
            .ForMember(d => d.Rank, o => o.MapFrom(s => s.Service.Rank))
            .ForMember(d => d.RankDate, o => o.MapFrom(s => s.Service.RankDate))
            .ForMember(d => d.RankNextDate, o => o.MapFrom(s => s.Service.RankNextDate))
            .ForMember(d => d.GradeFek, o => o.MapFrom(s => s.Service.GradeFek))
            .ForMember(d => d.Directorate, o => o.MapFrom(s => s.Service.Directorate))
            .ForMember(d => d.Sector, o => o.MapFrom(s => s.Service.Sector))
            .ForMember(d => d.Department, o => o.MapFrom(s => s.Service.Department))
            .ForMember(d => d.Office, o => o.MapFrom(s => s.Service.Office))
            .ForMember(d => d.WorkDirectorate, o => o.MapFrom(s => s.Service.WorksDirectorate))
            .ForMember(d => d.WorkSector, o => o.MapFrom(s => s.Service.WorksSector))
            .ForMember(d => d.WorkDepartment, o => o.MapFrom(s => s.Service.WorksDepartment))
            .ForMember(d => d.WorkOffice, o => o.MapFrom(s => s.Service.WorksOffice))
            .ForMember(d => d.Id, o => o.Ignore())
            .ForMember(d => d.Am, o => o.Ignore())
            //.ForMember(d => d.DateAdded, o => o.Ignore())
            .ForMember(d => d.IsActive, o => o.Ignore())
            .ForMember(d => d.Children, o => o.Ignore());

        CreateMap<ChildDto, Children>()
            .ForMember(d => d.Id, o => o.Ignore())
            .ForMember(d => d.EmployeeId, o => o.Ignore())
            .ForMember(d => d.ChildBirth, o => o.MapFrom(s => s.ChildBirth ?? default))
            .ForMember(d => d.ChildDateFrom, o => o.MapFrom(s => s.ChildDateFrom ?? default))
            .ForMember(d => d.ChildDateTo, o => o.MapFrom(s => s.ChildDateTo ?? default))
            .ForMember(d => d.ChildSchoolDesc, o => o.MapFrom(s => s.ChildSchoolDesc ?? default));

        CreateMap<ExperienceDto, Experience>()
            .ForMember(d => d.Id, o => o.Ignore())
            .ForMember(d => d.Am, o => o.Ignore())
            .ForMember(d => d.DateFrom, o => o.MapFrom(s => s.DateFrom ?? default))
            .ForMember(d => d.DateTo, o => o.MapFrom(s => s.DateTo ?? default))
            .ForMember(d => d.DateCouncil, o => o.MapFrom(s => s.DateCouncil ?? default));

        CreateMap<StudyDto, Studies>()
            .ForMember(d => d.Id, o => o.Ignore())
            .ForMember(d => d.Am, o => o.Ignore())
            .ForMember(d => d.Date, o => o.MapFrom(s => s.Date ?? default))
            .ForMember(d => d.DateRequired, o => o.MapFrom(s => s.DateRequired ?? default));
    }
}