import { z } from "zod";

export const employeeServiceFormSchema = z.object({
    workRelation: z.string().min(1, "Η σχέση εργασίας είναι υποχρεωτική").refine(v => v !== "-1", "Η σχέση εργασίας είναι υποχρεωτική"),
    category: z.string().min(1, "Η κατηγορία είναι υποχρεωτική").refine(v => v !== "-1", "Η κατηγορία είναι υποχρεωτική"),
    specialty: z.string().min(1, "Η ειδικότητα είναι υποχρεωτική").refine(v => v !== "-1", "Η ειδικότητα είναι υποχρεωτική"),
    branch: z.string().min(1, "Ο κλάδος είναι υποχρεωτικός").refine(v => v !== "-1", "Ο κλάδος είναι υποχρεωτικός"),
    position: z.string().min(1, "Η θέση στην υπηρεσία είναι υποχρεωτική").refine(v => v !== "-1", "Η θέση στην υπηρεσία είναι υποχρεωτική"),
    employmentType: z.string().min(1, "Η θέση είναι υποχρεωτική").refine(v => v !== "-1", "Η θέση είναι υποχρεωτική"),
    hireDate: z.string().min(1, "Η ημερομηνία πρόσληψης είναι υποχρεωτική").refine(v => v !== "1900-01-01", "Η ημερομηνία πρόσληψης είναι υποχρεωτική"),
    fek: z.string().optional(),
    salaryCode: z.string().min(1, "Ο κωδικός μισθοδοσίας είναι υποχρεωτικός"),
    mk: z.string().optional(),
    mkDate: z.string().optional(),
    mkNextDate: z.string().optional(),
    rank: z.string().optional(),
    rankDate: z.string().optional(),
    rankNextDate: z.string().optional(),
    gradeFek: z.string().optional(),
    directorate: z.number().optional(),
    sector: z.number().optional(),
    department: z.number().optional(),
    office: z.number().min(2).optional(),
    worksDirectorate: z.number().optional(),
    worksSector: z.number().optional(),
    worksDepartment: z.number().optional(),
    worksOffice: z.number().optional(),
});

export type EmployeeServiceFormData = z.infer<typeof employeeServiceFormSchema>;

export const emptyService: EmployeeServiceFormData = {
    workRelation: "-1",
    category: "-1",
    specialty: "-1",
    branch: "-1",
    position: "-1",
    employmentType: "-1",
    hireDate: "1900-01-01",
    fek: "",
    salaryCode: "",
    mk: "1",
    mkDate: "1900-01-01",
    mkNextDate: "1900-01-01",
    rank: "",
    rankDate: "1900-01-01",
    rankNextDate: "1900-01-01",
    gradeFek: "",
    directorate: undefined,
    sector: undefined,
    department: undefined,
    office: undefined,
    worksDirectorate: undefined,
    worksSector: undefined,
    worksDepartment: undefined,
    worksOffice: undefined,
};